### ISSUE TITLE
npm start doesn't work npm build doesn't work

### ISSUE THREAD

**Issue by togakangaroo** [alexweber/es6-jspm-gulp-boilerplate#3]
Ok, so coming here from a thread on karma-jspm about how you got tests working.

I'm trying to run your boilerplate and hitting issues right away.

So out-of-the-box 

```
> npm install;
> npm start;
```

Starts the site but it errors as both
- GET http://localhost:8080/css/app.css 
- GET http://localhost:8080/lib/system.js 

404.

So I try `npm test` and ... well, seem to get errors there as well.

Ok, so then I try `npm build` and get errors

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild es6-jspm-gulp-boilerplate@0.0.1
6 info build es6-jspm-gulp-boilerplate@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info es6-jspm-gulp-boilerplate@0.0.1 Failed to exec build script
9 verbose stack Error: es6-jspm-gulp-boilerplate@0.0.1 build: `gulp build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid es6-jspm-gulp-boilerplate@0.0.1
11 verbose cwd W:\es6-jspm-gulp-boilerplate
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error es6-jspm-gulp-boilerplate@0.0.1 build: `gulp build`
17 error Exit status 1
18 error Failed at the es6-jspm-gulp-boilerplate@0.0.1 build script 'gulp build'.
18 error This is most likely a problem with the es6-jspm-gulp-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp build
18 error You can get their info via:
18 error     npm owner ls es6-jspm-gulp-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

I'm on Windows 8.1 but I don't see anything in this log that would matter. Is this currently in a working state?

**Comment by togakangaroo** [comment]
Investigating further, here's the offender

```
> es6-jspm-gulp-boilerplate@0.0.1 buildjs W:\es6-jspm-gulp-boilerplate
> jspm bundle-sfx js/app dist/app.min.js --minify --skip-source-maps

     Building the single-file sfx bundle for js/app...

err  Error: Error loading "js/app" at file:W:/es6-jspm-gulp-boilerplate/src/js/app.js
     Error loading "npm:babel-core@5.5.6" at file:W:/es6-jspm-gulp-boilerplate/src/lib/npm/babel-core@5.5.6.js
     ENOENT, open 'W:\es6-jspm-gulp-boilerplate\src\lib\npm\babel-core@5.5.6.js'
         at Error (native)
```

**Comment by alexweber** [comment]
@togakangaroo Thanks for tracking this down!
